CREATE TABLE `Company`(
	`Company` VARCHAR(40) NOT NULL,
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`Company`)
);
ALTER TABLE `Company`
	ADD CONSTRAINT `fe927333bf740e1d8bd6a09d832956` UNIQUE KEY(`Company`);
