CREATE TABLE `Discipline`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`Discipline` VARCHAR(40) NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`Discipline`)
);
ALTER TABLE `Discipline`
	ADD CONSTRAINT `148f109d9706a19865dd319e629779` UNIQUE KEY(`Discipline`);
