CREATE TABLE `Hazard`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`Hazard` VARCHAR(40) NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`Hazard`)
);
ALTER TABLE `Hazard`
	ADD CONSTRAINT `5b3e73fda8aadf58ffb464a7a7d49f` UNIQUE KEY(`Hazard`);
