CREATE TABLE `Risks`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`Risks` VARCHAR(40) NOT NULL,
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`Risks`)
);
ALTER TABLE `Risks`
	ADD CONSTRAINT `3d201e35de2563be68bf651897031c` UNIQUE KEY(`Risks`);
