CREATE TABLE `Rules`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`Rules` VARCHAR(40) NOT NULL,
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`Rules`)
);
ALTER TABLE `Rules`
	ADD CONSTRAINT `3cb2ab1c8719509fd306fd14740126` UNIQUE KEY(`Rules`);
