CREATE TABLE `WorkingArea`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	`WorkingArea` VARCHAR(40) NOT NULL,
	PRIMARY KEY(`WorkingArea`)
);
ALTER TABLE `WorkingArea`
	ADD CONSTRAINT `52e87f47c0fe0d75661287b79ba407` UNIQUE KEY(`WorkingArea`);
